### ISSUE TITLE
Support tz2, tz3 addresses

### ISSUE THREAD

**Issue by oldominion** [gimmix-org/primitive-objkts#1]
tz2 and tz3 are also valid prefixes for Tezos addresses. Please can you allow those? Doesn't let me add one currently.

**Comment by shahruz** [comment]
@oldominion Sure. Do you have an example address or two that I can use to test?

**Comment by oldominion** [comment]
As far as I know, the easiest way to make one is with Kukai.app wallet using DirectAuth with Twitter. Those all seem to be tz2 addresses!

**Comment by shahruz** [comment]
@oldominion This is now updated.
